### PR TITLE
Patch fix thumbnail and other attributes

### PR DESCRIPTION
**Pull request by sinan-evanshunt**
Building on @davejtoews work and his pull request https://github.com/nathancox/silverstripe-embedfield/pull/14
I have patched the thumbnail URL and the thumbnail width and height as well as a few other attributes that were not working with the new code from the embed module.

### CODE REVIEW

**Comment by davejtoews** [comment]
@sinan-evanshunt do the Type, Width, and Height properties exist on the new API? 

The original had 

```php
$this->Type = $info->type;
$this->Width = $info->getWidth();
$this->Height = $info->getHeight();
```

I had commented those out, and you've restored the rest of the items I commented out but not those three. Width and Height seem to be distinct from ThumnailWidth and ThumbnailHeight.

**Comment by sinan-evanshunt** [comment]
That must have been a mistake on my side. 
```
$this->Width = $info->getWidth();
$this->Height = $info->getHeight();
```
Don't exist anymore. I'll fix it.

**Comment by sinan-evanshunt** [comment]
```
$this->Type 
$this->Width
$this->Height
```
Should now populate if the oEmbed provides them.
This change has been committed to this pull request.

**Comment by davejtoews** [comment]
This work was merged in in #16, closing

**Pull request closed without merging**
